### ISSUE TITLE
Unable to find theme package

### ISSUE THREAD

**Issue by watatomo** [curegit/line-theme-downloader#1]
I'm trying to get these ([1](https://store.line.me/themeshop/product/4cf9dc33-643e-4ff8-9254-044655f5ca2a/ja) + [2](https://store.line.me/themeshop/product/9197b06d-735d-4804-982c-4c35130d6080/ja)) themes, but the script keeps returning `No such theme package (possibly network error)` (there's no network error).

I'm using bash with this example code: `./download.sh f92efd5f-08c8-47cd-bbaa-df40f282315a`. Adding a version integer didn't work either.

I did end up finding the URL for the themes, though.

- `http://dl.shop.line.naver.jp/themeshop/v1/products/4c/f9/dc/4cf9dc33-643e-4ff8-9254-044655f5ca2a/38/IOS/theme.zip`
- `http://dl.shop.line.naver.jp/themeshop/v1/products/91/97/b0/9197b06d-735d-4804-982c-4c35130d6080/38/IOS/theme.zip`

**Comment by curegit** [comment]
Hi, I'm sorry for the late reply.

I tested the script with [those](https://store.line.me/themeshop/product/9197b06d-735d-4804-982c-4c35130d6080/ja) [packages](https://store.line.me/themeshop/product/4cf9dc33-643e-4ff8-9254-044655f5ca2a/ja) you tried.
However, it worked fine, and they were downloaded successfully.

Does the problem still occur?
I'm afraid of some environmental problems.

Check if cURL works properly via command like this:
```
curl -fL http://dl.shop.line.naver.jp/themeshop/v1/products/91/97/b0/9197b06d-735d-4804-982c-4c35130d6080/38/IOS/theme.zip > /dev/null && echo "OK"
```

And please tell me more information (OS, bash version, curl version etc.)

**Comment by watatomo** [comment]
As expected. Perhaps I don't have something installed.

This is the output I got.
![image](https://user-images.githubusercontent.com/23179278/88360744-b4dea780-cd2b-11ea-8b9d-af25ac79a100.png)

On Bash:
![image](https://user-images.githubusercontent.com/23179278/88361039-97f6a400-cd2c-11ea-8d0c-7d1ef1a8d413.png)

I'm on Windows 10, curl 7.55.1 and bash 4.4.23.

**Comment by curegit** [comment]
I figured out the problem.
The Bash script seems to always fail on MSYS because it uses the output redirection `> /dev/null` expecting a UNIX filesystem (I wonder why MSYS doesn't provide this).
I will try to fix the script so that it can be run on both Unix and Windows.
Or I will write about the compatibility in the README.

By the way, I recommend you use the Powershell script because you have Windows 10.

Open Powershell prompt, and execute like:

```
.\download.ps1 4cf9dc33-643e-4ff8-9254-044655f5ca2a
```

If you get permission errors, bypass them like this:

```
powershell -ExecutionPolicy Bypass -command .\download.ps1 4cf9dc33-643e-4ff8-9254-044655f5ca2a
```

I hope these solutions work.

**Comment by watatomo** [comment]
Ah, typical Windows. The last solution worked. Thank you!
